### ISSUE TITLE
ReferenceError: fom_init_login_form is not defined

### ISSUE THREAD

**Issue by marcboeker** [Fiedzia/Fang-of-Mongo#1]
hi,

after starting fang-of-mongo i'm receiving the following error as javascript alert.
<code>ReferenceError: fom_init_login_form is not defined</code>
the connect button is also missing.

thanks and cheers,
marc

**Comment by Fiedzia** [comment]
It seems like incorrect path to static files.
Does this url works:
http://localhost:8000/static/fom/js/fangofmongo_login.js ?
Please see INSTALL file and check if paths in settings.py are set correctly.

**Comment by marcboeker** [comment]
ah long time no django development :) now i remember of the settings.py. after adjusting both paths, i can see a beautiful jquery UI.
it looks very promising. i'm excited about new versions.
thanks + cheers marc
